#!/usr/bin/env perl

use Mojolicious::Lite;

use Config::JFDI;
my $cfg = Config::JFDI->new(name => 'config')->get;

use Directory::Queue;
my $Q = Directory::Queue->new(%{ $cfg->{texqueue} });

sub startup {
    my $self = shift;
    $self->types->type(tex => 'text/tex');
}
get '/' => 'index';

get '/print' => sub {
    my $self = shift;

    my $issue = $self->param('issue');
    # now to make a PDF, yay!

    $self->app->log->debug("OMG!! wanna print $issue");
    $self->stash(key => $issue);
    $self->stash(summary => $self->param('summary') || '');
    $self->stash(description => $self->param('description') || '');
    $self->stash(reporter => $self->param('reporter') || '');
    my $tex = $self->render_partial('print', format => 'tex');

    $self->app->log->debug("tex: " . $tex);
    $Q->add(tex=> "$tex") or $self->app->log->error("Could not add TEX to PDFer queue");
    $self->render(text => 'ISSUE PRINTED (' . $issue . ")\n");
};
app->start;

__DATA__

@@ index.html.ep
% layout 'funky';
We don't do much here, we print KANBAN cards for now!

@@ layouts/funky.html.ep
<!doctype html><html>
    <head><title>JIRA Print-server, yay</title></head>
    <body><%== content %></body>
</html>

@@ print.tex.ep
\documentclass[30pt, Screen4to3]{foils}
\usepackage{slidedesign}
\usepackage{bookmark}
\begin{document}
\foilhead{<%= $key %>: <%= $summary %>}
\begin{itemize}
\item <%= reporter %>
\end{itemize}

<%= description %>

\end{document}

