#!/usr/bin/env perl

use Mojolicious::Lite;
use ZeroMQ qw(ZMQ_PUB ZMQ_REQ);

my ($host, $port);
$host ||= '127.0.0.1';
$port ||= 5566;

my $ctxt = ZeroMQ::Context->new();
my $sock = $ctxt->socket(ZMQ_PUB) or die "Error in socket aqusision";
$sock->bind( "tcp://$host:$port" );
sub startup {
    my $self = shift;
    $self->types->type(tex => 'text/tex');
}
get '/' => 'index';

get '/print' => sub {
    my $self = shift;

    my $issue = $self->param('issue');
    # now to make a PDF, yay!

    $self->app->log->debug("OMG!! wanna print $issue");
    $self->stash(key => $issue);
    $self->stash(summary => $self->param('summary'));
    my $tex = $self->render_partial('print', format => 'tex');

    $self->app->log->debug("tex: " . $tex);
    $sock->send($tex) or die "Could not comunicate to 0MQ socket";
    $self->render(text => 'ISSUE PRINTED (' . $issue . ")");
    $self->app->log->debug("result: " . $self->res->body);
};
app->start;

__DATA__

@@ index.html.ep
% layout 'funky';
We don't do much here, we print KANBAN cards for now!

@@ layouts/funky.html.ep
<!doctype html><html>
    <head><title>JIRA Print-server, yay</title></head>
    <body><%== content %></body>
</html>

@@ print.tex.ep
\documentclass[30pt, Screen4to3]{foils}
\usepackage{slidedesign}
\usepackage{bookmark}
\begin{document}
\foilhead{<%= $key %>: <%= $summary %>}
\foilhead{<%= $key %>: <%= $summary %>}
\end{document}

