#!/usr/bin/env perl

use strict;
use warnings;
use Directory::Queue;

use File::Temp qw(tempfile);
use File::Basename;
use File::Copy;

$ENV{TEXINPUTS} = ".:tex/:/usr/local/texlive/2010basic/:";

my $Q = Directory::Queue->new(path => 'tex-queue', schema => { tex => 'string' });

while (1) {
    my $m = $Q->next || $Q->first;
    unless ($m) {
        sleep 1; # lets not busy lock!
        next;
    }
    warn "got M: $m";
    next unless $Q->lock($m);
    my %message = $Q->get($m);
    my $message = $message{tex};
    $Q->remove($m);
    print "Got a request, yay\n";
    warn $message;
    my ($fh, $file) = tempfile( DIR => 'out', SUFFIX => '.tex', OPEN => 1 );
    print $fh "$message";
    close $fh;

    # Now to call latex etc.
    my $cmd = "TEXINPUTS=$ENV{TEXINPUTS} pdflatex -interaction=batchmode -output-directory=out $file";
    warn "running: $cmd";
    my $tex_out = `$cmd`;
    my $base = basename($file, qw(.tex));
    if (! -f  "out/$base.pdf" or $?) {
        warn "Error generating PDF: $? $tex_out";
        next;
    } else {
        warn "Produced PDF: out/$base.pdf";
    }
    my @trash = ("out/$base.tex", "out/$base.log", "out/$base.aux");
    unlink @trash or warn "Error cleaning up @trash: $!";

    move("out/$base.pdf", "queue/");

}

