#!/usr/bin/env perl

use strict;
use warnings;

use Directory::Queue;

use Net::CUPS;
use Net::CUPS::Destination;

my $dest = Net::CUPS->new()->getDestination();
$dest->addOption('landscape', 'on');
$dest->addOption('sides', 'two-sided-short-edge');
$dest->addOption('fit-to-page', 'on');

my $O = Directory::Queue->new(path => 'queue', schema => { path => 'string'});

while (1) {
    my $e = $O->next || $O->first;
    unless ($e) {
        sleep 1;
        next;
    }
    my %e = $O->get($e);

    # Print it
    # XXX: This should be async ideally, since we are in an event loop
    warn "  -- >> Printing";
    $dest->printFile($e{path}, "Printing file from queue");

    # remove it!
    unlink($e{path}) or warn "error unlinking: $e";
}
